Issue 60 tables accordion
hlxsites/stewart pull request #109
Opened 2023-08-08 22:52 UTC by fperez-leappoint

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #60 

If your PR introduces a new block/black varaint, please update the block library https://main--stewart--hlxsites.hlx.page/tools/sidekick/library/library.html

Test URLs:
- Before: https://main--stewart--hlxsites.hlx.live/
- After: https://issue-60-tables-accordion--stewart--hlxsites.hlx.page/drafts/fperez/sureclose-advantage

2023-08-09 21:12 UTC, shsteimer requested changes

2023-08-09 21:12 UTC, shsteimer commented on blocks/accordion/accordion.js
> -    const button = createElement('button', {
I think for semantic/accessibility reasons, this does need to be a button. otherwise, you have an h2 that acts like a button.

2023-08-09 21:12 UTC, shsteimer commented on blocks/accordion/accordion.js
> +    }
imho this is too specific, without a good reason being so. the accordion content should support anything, images/other blocks/etc. not just paragraphs and tables. should be as simple as taking all items in the row and placing them in the panel.

2023-08-09 22:06 UTC, fperez-leappoint commented on blocks/accordion/accordion.js
> +    }
fixing it

2023-08-09 22:06 UTC, fperez-leappoint commented on blocks/accordion/accordion.js
> -    const button = createElement('button', {
Changed

2023-08-09 22:12 UTC, usman-khalid requested changes

2023-08-09 22:12 UTC, usman-khalid commented on blocks/accordion/accordion.css
> +    color: #007dbd;
Can we please use `var(--clr-primary)` here?

2023-08-09 22:12 UTC, usman-khalid commented on blocks/accordion/accordion.css
> +    background-color: #f2f2f2;
Same here. `--clr-gray`. Looks like a lot of hex values can be replaced with a CSS variable in this file.

2023-08-09 22:12 UTC, usman-khalid commented on blocks/accordion/accordion.js
> +    const panelText = accordionItem.querySelector('p');
What if we need to add headings to accordion panels? I think this needs to handle more types of content.

2023-08-09 22:12 UTC, fperez-leappoint commented on blocks/accordion/accordion.js
> +    const panelText = accordionItem.querySelector('p');
already on it

2023-08-09 22:13 UTC, usman-khalid commented on blocks/accordion/accordion.js
> +    const panelText = accordionItem.querySelector('p');
Sorry, this comment is redundant — missed Sean's comment below which is saying the same thing. Resolving this.

2023-08-09 22:16 UTC, usman-khalid commented
Please update the block library accordion page based on this new approach: https://issue-60-tables-accordion--stewart--hlxsites.hlx.page/library/blocks/accordion

2023-08-09 22:42 UTC, usman-khalid requested changes

2023-08-09 22:42 UTC, usman-khalid commented on blocks/accordion/accordion.css
> +main .accordion .accordion-item .accordion-item-trigger {
I think this needs a `width: 100%` for a11y reasons, it's currently only clickable where the text is.

<img width="1469" alt="Screen Shot 2023-08-09 at 6 29 04 PM" src="https://github.com/hlxsites/stewart/assets/9199192/763ac9a0-730f-4e67-9708-5b8c59e4cf2b">

2023-08-09 22:42 UTC, usman-khalid commented on blocks/accordion/accordion.js
> +      panel.classList.toggle(classNames.accordionItemActive);
The class being toggled here is toggling visibility by setting the `opacity` on the panel. This is causing the elements inside it to technically still be available to interact with. If you hover over the links in one of the tables while that panel is still closed, you can actually click them. It's also throwing off accessibility because when tabbing through it, it's going overall the links and such in that panel before moving on to the next one.

We should toggle `visibility` in the classes associated with this logic or stick to the `hidden` attribute.

2023-08-21 13:16 UTC, fperez-leappoint commented on blocks/accordion/accordion.css
> +main .accordion .accordion-item .accordion-item-trigger {
done

2023-08-21 13:16 UTC, fperez-leappoint commented on blocks/accordion/accordion.js
> +      panel.classList.toggle(classNames.accordionItemActive);
done

2023-08-21 20:38 UTC, shsteimer approved these changes

2023-08-21 22:05 UTC, usman-khalid approved these changes

2023-08-22 14:06 UTC, merged